### PR TITLE
feat: add repo-dir for cve omit

### PR DESCRIPTION
**Pull request by darosale**

### CODE REVIEW

**Comment by darosale** [comment]
https://github.com/open-toolchain/tekton-catalog/pull/260

**Comment by darosale** [comment]
https://github.ibm.com/oneibmcloud/CD-CRA/issues/731

**Review by jauninb — CHANGES_REQUESTED** [review]
Needs some change in the task for default value

**Review by jauninb — APPROVED** [review]
LGTM

**Pull request merged**
